apps/smokex_web/lib/smokex_web/router.ex
defmodule SmokexWeb.Router do
  use SmokexWeb, :router

  use Pow.Phoenix.Router
  use Sentry.PlugCapture
  use Pow.Extension.Phoenix.Router, extensions: [PowResetPassword]

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, {SmokexWeb.LayoutView, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :protected do
    plug Pow.Plug.RequireAuthenticated,
      error_handler: Pow.Phoenix.PlugErrorHandler
  end

  pipeline :basic_auth do
    plug(SmokexWeb.Plugs.BasicAuth)
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  pipeline :skip_csrf_protection do
    plug(:accepts, ["html"])
    plug(:fetch_session)
    plug(:fetch_flash)
    plug(:put_secure_browser_headers)
  end

  pipeline :stripe_webhooks do
    plug SmokexWeb.Payments.Stripe.Webhooks.Plug
  end

  pipeline :pow_email_layout do
    plug :put_pow_mailer_layout, {SmokexWeb.LayoutView, :email}
  end

  scope "/" do
    pipe_through [:browser, :pow_email_layout]

    pow_routes()
    pow_extension_routes()
  end

  scope "/", SmokexWeb do
    pipe_through([:skip_csrf_protection, :api])

    scope "/auth" do
      get "/slack/callback", Callbacks.Slack, :callback
    end

    scope "/payments/stripe" do
      pipe_through(:stripe_webhooks)

      post("/webhooks", Payments.Stripe.Webhooks, :handle_webhook)
    end
  end

  scope "/workflow_test", SmokexWeb.Controllers.WorkflowTest do
    pipe_through([:skip_csrf_protection, :api])

    post "/login", TestEndpoint, :login
    get "/players", TestEndpoint, :get_players
    get "/best/:team", TestEndpoint, :best_laker
    put "/message", TestEndpoint, :message
  end

  scope "/", SmokexWeb do
    pipe_through :browser

    get "/sitemap.xml", Controllers.Sitemap, :build

    get "/", Controllers.Landing, :show
    get "/landing", Controllers.Landing, :show
    get "/privacy-policy", Controllers.Legal, :privacy_policy
    get "/terms-and-conditions", Controllers.Legal, :terms_and_conditions

    live "/blog", BlogLive.Show
    live "/pricing", PricingLive.Show
    live "/docs", DocumentationLive.Show
    live "/getting-started", WelcomeLive.Show

    scope "/" do
      pipe_through :protected

      live "/stats", StatsLive.Show

      scope "/my-account", MyAccountLive do
        live "/", Show
        live "/edit", Edit
        live "/billing", Billing
        live "/integrations/slack", Integrations.Slack
        live "/secrets", Administration.Secrets.Show
        live "/secrets/new", Administration.Secrets.New
        live "/secrets/:name/edit", Administration.Secrets.Edit
      end

      live "/workflows", PlansDefinitionsLive.List
      live "/workflows/new", PlansDefinitionsLive.New
      live "/workflows/:id", PlansDefinitionsLive.Show
      live "/workflows/:id/edit", PlansDefinitionsLive.Edit

      live "/executions", PlansExecutionsLive.List
      live "/executions/:id", PlansExecutionsLive.Show

      scope "/payments" do
        get "/success", Payments.Stripe.Callbacks, :success
        get "/cancel", Payments.Stripe.Callbacks, :cancel
      end
    end
  end

  # Other scopes may use custom stacks.
  # scope "/api", SmokexWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  import Phoenix.LiveDashboard.Router

  scope "/" do
    pipe_through :browser
    pipe_through :basic_auth
    live_dashboard "/boat/dog/dashboard", metrics: SmokexWeb.Telemetry
  end

  #
  # Plug function needed to add the base layout to pow emails, for more info
  # see: https://hexdocs.pm/pow/Pow.Phoenix.Mailer.Mail.html#content
  #
  defp put_pow_mailer_layout(conn, layout), do: put_private(conn, :pow_mailer_layout, layout)
end

apps/smokex_web/lib/smokex_web/views/controllers/landing_view.ex
defmodule SmokexWeb.Controllers.LandingView do
  use SmokexWeb, :view
end

apps/smokex_web/lib/smokex_web/views/controllers/legal_view.ex
defmodule SmokexWeb.Controllers.LegalView do
  use SmokexWeb, :view
end

apps/smokex_web/lib/smokex_web/views/controllers/pricing_view.ex
defmodule SmokexWeb.Controllers.PricingView do
  use SmokexWeb, :view
end

apps/smokex_web/lib/smokex_web/views/controllers/sitemap_view.ex
defmodule SmokexWeb.Controllers.SitemapView do
  use SmokexWeb, :view
end

apps/smokex_web/lib/smokex_web/templates/controllers/landing/show.html.eex
<div id="wrapper" class="has-text-centered-mobile">
  <section id="landing-hero" class="section hero highlightable">
    <div class="hero-container container  pt-5">
      <div class="content is-large">
        <h1 class="title">Monitor and test you applications. With no code.</h1>
        <p class="mb-5">
        <span class="is-hidden-mobile">
          With Smokex you can monitor the uptime of your applications, automate
          your HTTP requests, or create tests to validate your applications.
        </span>
        </p>

        <%= link "Sign up for free", class: "button is-primary is-large", to: Routes.pow_registration_path(@conn, :new) %>
      </div>

      <img src="<%= Routes.static_path(@conn, "/images/landing.png") %>" class="hero-image" alt="Landing image"/>
    </div>
  </section>

  <section id="features" class="section pt-6 highlightable">
    <div class="container">
      <h2 class="title is-1 mb-6">A powerful tool to monitor & test your applications</h2>
      <div class="columns">
        <div class="column is-6">
          <h4 class="title is-spaced"><ion-icon name="bug-outline"></ion-icon>
            Test anything in a heartbeat</h4>
          <p class="subtitle">Create tests for your applications without
          changing anything in your current projects.</p>
        </div>
        <div class="column is-6">
          <h4 class="title is-spaced"><ion-icon
              name="cloud-done-outline"></ion-icon> Monitor your uptime</h4>
          <p class="subtitle">Want to know immediately if your website or
          server goes down? Smokex will notify you if detects a problem!</p>
        </div>
      </div>
      <div class="columns">
        <div class="column is-6">
          <h4 class="title is-spaced"><ion-icon
              name="shield-outline"></ion-icon> Protect your product</h4>
          <p class="subtitle">Identify downtimes, performance issues, routing
          problems, errors... Smokex will send you an alert to your email and
          Slack.</p>
        </div>
        <div class="column is-6">
          <h4 class="title is-spaced"><ion-icon
              name="albums-outline"></ion-icon> Powerful & flexible</h4>
          <p class="subtitle">The powerful template engine allows our customer
          to automate almost anything to test and monitor their products.</p>
        </div>
      </div>
    </div>
  </section>

  <section id="get-started" class="section mt-6 highlightable">
    <div class="container mb-6">
      <h1 class="title is-1 mb-6">How it works</h1>
      <div class="columns reverse-row-order mt-6">

        <div class="column">
          <h1 class="title"><ion-icon name="albums-outline"></ion-icon> Create a workflow</h1>
          <p class="has-text-black paragraph"><%= live_patch "Create a
workflow", to: Routes.live_path(@conn, SmokexWeb.PlansDefinitionsLive.New) %>
containing for example, uptime checks or validations for your website or server. Check the <%= live_patch "documentation", to: Routes.live_path(@conn, SmokexWeb.DocumentationLive.Show) %> for more information on how it works.
          </p>
        </div>
        <div class="column has-text-centered">
          <img src="<%= Routes.static_path(@conn, "/images/landing-step-one.svg") %>" class="hero-image" alt="Landing image"/>
        </div>
      </div>
    </div>

    <br>
    <br>

    <div class="container mb-6">
      <div class="columns reverse-row-order">
        <div class="column has-text-centered">
          <img src="<%= Routes.static_path(@conn, "/images/landing-step-two.svg") %>" class="hero-image" alt="Landing image"/>
        </div>
        <div class="column">
          <h1 class="title"><ion-icon name="timer-outline"></ion-icon> Schedule or launch it manually</h1>
          <p class="has-text-black paragraph">
          After you create a workflow, you can schedule the executions using a
          <a href="https://crontab.guru/examples.html" target="_blank">cron
          sentence</a>. Want to run it on demand? You can also do it manually.
          </p>
        </div>
      </div>
    </div>

    <div class="container mb-6">
      <div class="columns reverse-row-order">
        <div class="column">
          <h1 class="title"><ion-icon name="cafe-outline"></ion-icon> Get a coffee, we will take it from here</h1>
          <p class="has-text-black paragraph">
          We will run your workflow with the uptime checks, tests... Now you
          can sit and relax, if we detect any problem will send you an alert
          immediately via email or Slack with the details you need.
          </p>
        </div>
        <div class="column has-text-centered">
          <img src="<%= Routes.static_path(@conn, "/images/landing-step-three.svg") %>" class="hero-image" alt="Landing image"/>
        </div>
      </div>
    </div>

    <br>
    <br>
  </section>

  <section id="example" class="section pt-6 highlightable cheatsheet">
    <div class="container">
      <h2 class="title is-1 mb-4">Simple scenario, monitor uptime of your application</h2>
      <div class="columns">
        <div class="column is-6">
          <p class="has-text-black paragraph mb-5">
          Get notified when your site goes down, you will <strong>immediately
            get an email or Slack message</strong>.
          </p>
          <pre class="box" phx-hook="LoadPrismjs">
  <code class="language-yaml"><span>- get:
      host: "http://smokex.io"
      expect:
        status_code: 200</span></code>
          </pre>
        </div>
      </div>
    </div>
  </section>

  <section id="signup" class="section highlightable">
    <div class="container">
      <h3 class="title is-1 mb-6">
        Start monitoring your applications for free!
      </h3>

      <div class="columns">
        <div class="column is-6">
          <img src="<%= Routes.static_path(@conn, "/images/landing-signup.svg") %>" class="hero-image" alt="Landing image"/>
          </p>
        </div>

        <%= form_for @changeset, :registration, [class: "column is-6", as: :user, csrf_token: Phoenix.Controller.get_csrf_token()], fn f -> %>
            <div class="field">
              <label class="label">Email</label>
              <div class="control">
                <%= text_input f, Pow.Ecto.Schema.user_id_field(@changeset),
class: "input is-medium", type: "email",
placeholder: "luke@skywalker.com" %>
              </div>
            </div>

            <div class="field">
              <label class="label">Password</label>
              <div class="control">
                <%= password_input f, :password, class: "input is-medium",
placeholder: "yourstrongestpassword" %>
              </div>
            </div>

            <div class="field">
              <label class="label">Confirm password</label>
              <div class="control">
                <%= password_input f, :password_confirmation,
placeholder: "yourstrongestpassword", class: "input is-medium" %>
              </div>
            </div>

            <div class="field">
              <div class="control">
                <p>By creating an account you agree to the
                <%= link "terms and conditions", to: Routes.legal_path(SmokexWeb.Endpoint, :terms_and_conditions) %>
                and
                <%= link "privacy policy", to: Routes.legal_path(SmokexWeb.Endpoint, :privacy_policy) %>.
              </div>
            </div>


            <div class="field is-grouped">
              <div class="control">
                <button class="button is-outlined is-ligth">Sign up</button>
              </div>
            </div>
        <% end %>
      </div>
    </div>
  </section>
</div>